categoriesのmigrationファイルを作成
takumiTakahata/equipment_management_system pull request #11
Opened 2024-06-10 05:53 UTC by Ragamn

modelsフォルダにcategories.pyを追加しました。

2024-06-10 05:55 UTC, Raiki215 requested changes
2com @Ragamn

2024-06-10 05:55 UTC, Raiki215 commented on equipment_management/equipment_management_api/models/categories.py
> +        verbose_name_plural = 'Categories'
test

2024-06-10 05:55 UTC, Raiki215 commented on equipment_management/equipment_management_api/migrations/0002_category.py
> +                ('id', models.AutoField(primary_key=True, serialize=False)),
tttt

2024-06-10 05:59 UTC, Raiki215 commented on equipment_management/equipment_management_api/models/categories.py
> +    name = models.CharField(max_length=255)
カテゴリーの名前の桁255でいいの？

2024-06-10 06:01 UTC, Raiki215 requested changes
1か所修正お願いします。 @Ragamn

2024-06-10 06:06 UTC, Ragamn commented on equipment_management/equipment_management_api/models/categories.py
> +    name = models.CharField(max_length=255)
修正しました
https://github.com/takumiTakahata/equipment_management_system/pull/11/commits/4aeb9a8831f6271a7d5a9902c21f01cec67423b3

2024-06-10 06:07 UTC, takumiTakahata approved these changes
見ました

2024-06-10 06:07 UTC, Raiki215 approved these changes
確認しました。

2024-06-11 02:17 UTC, yoshiokaharuto approved these changes
確認しました

2024-06-11 02:17 UTC, merged