courseテーブルの修正
takumiTakahata/equipment_management_system pull request #14
Opened 2024-06-13 01:36 UTC by Ragamn

defaultをdb_defaultに変更

2024-06-13 01:37 UTC, yoshiokaharuto approved these changes
確認しました。

2024-06-13 01:38 UTC, Raiki215 commented on equipment_management/equipment_management_api/migrations/0001_initial.py
> +                ('name', models.CharField(max_length=255)),
255でいいの？

2024-06-13 01:39 UTC, Raiki215 requested changes
1か所考えてみて

2024-06-13 01:46 UTC, Ragamn commented
修正しました。
https://github.com/takumiTakahata/equipment_management_system/pull/14/commits/97a3dc4e8a074060a8ac6f17ce567cb48969df1f

2024-06-13 01:48 UTC, Ragamn commented on equipment_management/equipment_management_api/migrations/0001_initial.py
> +                ('name', models.CharField(max_length=255)),
修正しました。
https://github.com/takumiTakahata/equipment_management_system/pull/14/commits/97a3dc4e8a074060a8ac6f17ce567cb48969df1f

2024-06-13 01:49 UTC, Raiki215 approved these changes

2024-06-14 00:38 UTC, takumiTakahata approved these changes
確認しました

2024-06-14 00:38 UTC, merged